// Markdown summary export: an executive-readable view of a report. Pure and deterministic, LF line endings.
// Every value that originates in the pack (profile name, remediation text, category names) is escaped so it cannot
// break a table or carry raw HTML; the engine's own notes (scoring note, decision policy, disclaimer) are
// reproduced verbatim.
import { CATALOG } from './catalog';
import type { EvidencePack, Report, SubcategoryResult } from './types';

/** Escape text for a single Markdown line or table cell: `&` → `&amp;`, `<` → `&lt;`, `|` → `\|`, line breaks → spaces. */
export function escapeMarkdownCell(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/\|/g, '\\|')
    .replace(/\r\n|\r|\n/g, ' ');
}

function categoryName(subcategoryId: string): string {
  return CATALOG.find((s) => s.id === subcategoryId)?.categoryName ?? '';
}

function row(cells: (string | number)[]): string {
  return '| ' + cells.map((c) => (typeof c === 'number' ? String(c) : escapeMarkdownCell(c))).join(' | ') + ' |';
}

function statusCell(r: SubcategoryResult): string {
  const notes: string[] = [];
  if (r.override) notes.push(r.overrideValid ? 'override' : 'invalid override');
  if (r.warnings.length) notes.push(`${r.warnings.length} warning${r.warnings.length === 1 ? '' : 's'}`);
  return notes.length ? `${r.status} (${notes.join('; ')})` : r.status;
}

export function reportToMarkdown(report: Report, pack: EvidencePack): string {
  const esc = escapeMarkdownCell;
  const p = report.policy;
  const sufficient = report.results.filter((r) => r.status === 'sufficient').length;
  const notApplicable = report.results.filter((r) => r.status === 'not-applicable').length;
  const warnings = report.results.reduce((n, r) => n + r.warnings.length, 0);
  const out: string[] = [];

  out.push(`# Tessera report — ${esc(report.generatedFor)}`, '');
  out.push('_Educational prototype using synthetic evidence — not a certification, attestation or audit opinion. See Notes._', '');
  out.push(`- As of: ${esc(report.asOf)}`);
  out.push(`- Framework: ${esc(report.framework)}`);
  out.push(`- Subset: ${esc(report.subset)}`);
  out.push(`- Outcomes: ${report.results.length} (${sufficient} sufficient, ${report.gaps.length} in the gap register, ${notApplicable} not applicable)`);
  out.push(`- Evidence artifacts: ${pack.evidence.length} · Reviewer decisions: ${pack.decisions.length} · Reviewer warnings: ${warnings}`, '');

  out.push('## Rule policy', '');
  out.push(
    report.policyIsDefault
      ? 'Computed with the default policy (`tessera.policy/1`).'
      : 'Computed with a custom policy (`tessera.policy/1`); the full policy is embedded in the JSON report.',
    '',
  );
  out.push(row(['Parameter', 'Value']), '| --- | --- |');
  out.push(row(['agingMultiplier', p.agingMultiplier]));
  out.push(row(['decisionValidDays', p.decisionValidDays]));
  out.push(row(['minOverrideRationale', p.minOverrideRationale]));
  out.push(row(['sufficientCoverage', p.sufficientCoverage]));
  out.push(row(['minDistinctTypes', p.minDistinctTypes]));
  out.push(row(['separationOfDuties', String(p.separationOfDuties)]), '');

  out.push('## Functions', '');
  out.push(row(['Function', 'Sufficient', 'Assessed', 'Mean residual', 'Band']), '| --- | ---: | ---: | ---: | --- |');
  for (const f of report.rollups) {
    out.push(row([`${f.fn} — ${f.functionName}`, `${f.sufficient}/${f.count}`, f.assessed, f.meanResidual === null ? '—' : f.meanResidual.toFixed(2), f.band]));
  }
  out.push('');

  out.push('## Gap register', '');
  if (report.gaps.length === 0) {
    out.push('Every outcome in the subset is sufficient or not applicable.', '');
  } else {
    out.push(`${report.gaps.length} of ${report.results.length} outcomes are not sufficiently evidenced, ranked by residual exposure (priority × status exposure).`, '');
    out.push(row(['#', 'Outcome', 'Status', 'Priority', 'Residual', 'Band', 'Remediation']), '| ---: | --- | --- | ---: | ---: | --- | --- |');
    report.gaps.forEach((g, i) => {
      out.push(row([i + 1, `${g.subcategoryId} — ${categoryName(g.subcategoryId)}`, statusCell(g), g.priority, g.residual.toFixed(2), g.band, g.remediation ?? '']));
    });
    out.push('');
  }

  out.push('## Notes', '');
  out.push(`Scoring note: ${report.scoringNote}`, '');
  out.push(`Decision policy: ${report.decisionPolicy}`, '');
  out.push(`Disclaimer: ${report.disclaimer}`, '');
  out.push('---', '');
  out.push(`Generated by Tessera (educational prototype) for ${esc(report.generatedFor)} as of ${esc(report.asOf)}.`);
  return out.join('\n') + '\n';
}
